version: '3.8'
services:
  gitlab:
    image: repository.dimas-maryanto.com:8086/gitlab/gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        GITLAB_SHELL_SSH_PORT=10022
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 80:80
      - 1022:22
    volumes:
      - ./backups:/var/opt/gitlab/backups/
      - ./gitlab/gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json
      - gitlab_conf:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
    networks: 
      - gitlab_network
volumes:
  gitlab_conf:
  gitlab_data:
networks: 
  gitlab_network: